title: "Aditya J Shettigar"
description: "Security research, OSINT tools, CTF writeups and Project logs."
url: "https://adityajshettigar.github.io"
baseurl: ""
author: "Aditya J Shettigar"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - admin/